spring:
  application:
    name: order-service

  datasource:
    #url: ${DB_URL}
    url: jdbc:mysql://localhost:3307/order_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: mysql

    #url: ${DB_URL}
    #username: ${DB_USERNAME}
    #password: ${DB_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  flyway:
    locations: classpath:db/migration

server:
  port: 8083

inventory:
  url: http://localhost:8082
